### ISSUE TITLE
Add PHP fixing check to the CI (as GitHub action)

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#17]
There should be a dry run to check that PHP CS Fixer will not change anything.

**Comment by oliverklee** [comment]
Like this: https://github.com/MyIntervals/emogrifier/blob/master/composer.json#L77

**Comment by lukaszuznanski** [comment]
I think this issue can be closed https://github.com/TYPO3-Documentation/tea/blob/master/composer.json#L71

**Comment by oliverklee** [comment]
Indeed it can. Closing.
