### ISSUE TITLE
Migrate yaml-lint to phive

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Documentation/tea#201]
j13k/yaml-lint package is missing GPG signature and it's stopping us from using it via PHAR. I created issue https://github.com/j13k/yaml-lint/issues/29

**Comment by oliverklee** [comment]
We'll also need a new release of that tool first because the latest release cannot process multiple files in one go (which is we we currently are using the dev version): https://github.com/TYPO3-Documentation/tea/pull/207/checks?check_run_id=1969568828
