### ISSUE TITLE
Streamline the Composer scripts

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#240]
- use an array of commands instead of `&&` for executing two commands consecutively
- use `@php` to run a PHP script
- use `@composer` to run a Composer command
- make use of the fact that Composer temporarily  pushes the `bin/` dir to the top of the path while executing Composer scripts

(I haven't checked whether this actually will result in any changes for us.)

**Comment by lukaszuznanski** [comment]
- we don't use any `&&`
- we are using `@php` already
- we don't use any `@composer`

**Comment by oliverklee** [comment]
Okay, closing then. Thanks for checking this, @lukaszuznanski!
