### ISSUE TITLE
Difference to documentation and differences to core testing (e.g. nimut/testing-framework)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/tea#241]
There are some differences here to what is used in the official documentation ["Extension Testing"](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Testing/ExtensionTesting.html) and what is used in the core.

* IMHO, it would be good if at least the documentation for testing extensions and this repo use the same methods. 

* Even better would be, if the core and extension testing procedure overlap as much as possible because that would make contribution easier.

* also, if there are different ways to do things it might be helpful to explain this somewhere.

## Differences

1. typo3/testing-framework vs nimut/testing-framework
2. documentation and core uses runTests.sh script
3. ~~phpstan vs. codesniffer~~
4.  ...

**Comment by oliverklee** [comment]
@sypets Thanks for bringing this topic up!

We've discussed this, and I will provide a PR for the core docs to make this more clear, and also add a section on this topic to the Tea README.

**Comment by sypets** [comment]
@oliverklee Thanks. Sounds good.

I am not familiar enough with the 2 testing frameworks but might that be a possibility long-term to harmonize this, e.g. by making it more modular and having a common base testing-framework?

---

I have recently forked a core extension and am working on this as my own extension (linkvalidator => [brofix](https://github.com/sypets/brofix)). It already had tests based on `typo3/testing-framework` and I followed the [extension testing](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Testing/ExtensionTesting.html) page based on runTests.sh. Now, I looked at tea and I think it is great to have a common "best practice" extension, but I am reluctant to change everything - I would like to understand the implications first.

It would be cool if writing (and running tests) in core and in extensions would be very similar. I realize there are bound to be _some_ differences (e.g. GitHub vs. bamboo) but if it would be much less of a hassle if these were minimal.

**Comment by oliverklee** [comment]
@sypets I'd love these two testing frameworks to be harmonized or merged. (AFAIK, the nimut TF started out as a fork of the TYPO3 TF as the latter did not support multiple versions at the same time.)

Maybe someone (who?) could take up the task of …:
1. talking to the TYPO3 TF maintainers and come to a decision that it should support 2 TYPO3 versions
2. merge the nimut TF changes back into the TYPO3 TF

**Comment by DanielSiepmann** [comment]
Please let me provide info for each part:
>  IMHO, it would be good if at least the documentation for testing extensions and this repo use the same methods.

I don't think that will happen or make sense. As long as this repo uses nimut testing framework. That's a 3rd party project with own documentation and code base.

> Even better would be, if the core and extension testing procedure overlap as much as possible because that would make contribution easier.

Fully aggree here. But I guess only a very small part of API can be streamlined it won't change to much.

> also, if there are different ways to do things it might be helpful to explain this somewhere.

@oliverklee took the task to add this to official docs, see: https://github.com/TYPO3-Documentation/tea/issues/241#issuecomment-835448586 and https://gitlab.typo3.org/qa/internal-organization/-/blob/master/MeetingMinutes/2021/05/05.rst
> We believe there is no single good way.
Both ways have pros and cons. We will provide info to ease the decision.

And now let me add my own opinion:

The differences are not bound to contexts, e.g. GitLab, GitHub or Bamboo. Both frameworks are independent.
Nimut supports some APIs which might make sense in TYPO3 as well. The biggest difference: TYPO3 is used for TYPO3 itself. Therefore, it might be ahead in some areas (e.g. internal request submissions).

The big advantage of Nimut is support of multiple TYPO3 CMS versions. TYPO3 doesn't have this requirement. Each TYPO3 CMS version is bound to matching TYPO3 testing framework version.

Authors providing support for a single TYPO3 version can stick to TYPO3 testing framework, but are free to use anything else.
Authors providing support for multiple TYPO3 versions need to tweak their setup, or use Nimut instead.

I get the idea behind the question and understand the request to make things easier. But I think everything is as easy as possible. You have different requirements and solutions. It's the same as "I don't like there is TYPO3 and Wordpress, I want a single solution for websites". That's not how I think it works.

And I don't think TYPO3 will add the Burdon to maintain the testing framework for support with all the different versions.

Same for runTests.sh, that's an addition to the testing framework and a wrapper which uses a defined docker setup. You are free to ignore this and use your CI or local environment.

That's my opinion, and it probably doesn't help you. As Oliver said "someone" could work on that topic. But I won't do that, I don't see issues there. Instead, I would like to see more efforts in better APIs, e.g. support for in memory database (sqlite) and better request testing. But those things will come and partly are not even related to TYPO3 anymore. E.g. take command testing. Use TYPO3 testing framework, fetch the command from container and use Symfony command tester.

I still hope this comment helps in some way, e.g. understand differences, situation and possible solutions for individuals under their circumstances.

**Comment by sypets** [comment]
@DanielSiepmann @oliverklee Thank you for taking the time. 

I think the general issues I was trying to raise has been understood (make it easy for beginners, streamline different ways to do things, sync docs with official repos for best practice). If and how this can / should be solved is another thing.

Please also bear in mind, sometimes small things help - e.g. adding a note on top of the extension testing page link to this repo or appropriate information. 

I think I will have a better understanding once I try out this procedure here and nimut framework.

**Comment by sypets** [comment]
See also #94.
