### ISSUE TITLE
Allow newlines in ternary

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Documentation/tea#337]
I've just stumbled over the same as in https://github.com/squizlabs/PHP_CodeSniffer/issues/3377#issuecomment-860028311 and have seen that @oliverklee had that request as well.

What do you think about
```
<rule ref="Squiz.WhiteSpace.OperatorSpacing">
    <properties>
        <property name="ignoreNewlines" value="true" />
    </properties>
</rule>
```
in https://github.com/TYPO3-Documentation/tea/blob/main/phpcs.xml?

**Comment by oliverklee** [comment]
@jonaseberle Yes, let's have this! Care to create a PR for this?
