### ISSUE TITLE
Improve the coverage reports

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#345]
- have a nicer-looking coverage badge
- get coverage numbers in pull requests (and have a decrease in coverage fail the build)
- have a coverage report with the code lines marked as covered/not covered

Tools I'm looking into:
- https://scrutinizer-ci.com/pricing (not free for OSS projects?)
- https://www.codacy.com/pricing (free for OSS projects)
- https://coveralls.io/pricing (free for OSS projects)

**Comment by oliverklee** [comment]
Coveralls can comment on PRs, it seems: https://github.com/TYPO3/Fluid/pull/586#issuecomment-1046196413

**Comment by lukaszuznanski** [comment]
> Coveralls can comment on PRs, it seems: [TYPO3/Fluid#586 (comment)](https://github.com/TYPO3/Fluid/pull/586#issuecomment-1046196413)

Should we switch to Coveralls? This looks way nicer and migration is relatively easy. I could provide pull request.

**Comment by oliverklee** [comment]
> Should we switch to Coveralls? This looks way nicer and migration is relatively easy. I could provide pull request.

Yes, although I'd like to compare Coverals and Codacy (which are both free for OSS projects). Maybe we can have a PR each for both and compare.
