### ISSUE TITLE
Badge for the GitLab CI pipeline status shows "pipeline unknown"

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#355]
It should be green (or red) instead, and have a success or failure text.

**Comment by lukaszuznanski** [comment]
I'm unable to access gitlab project settings to check it. I will ask for additional perrmisions.

**Comment by DanielSiepmann** [comment]
You now should have necessary access rights @lukaszuznanski.

**Comment by lukaszuznanski** [comment]
Fixed, it will show current status, currently failing, due to tests on php7.2 (I will push PR)
