### ISSUE TITLE
PHP fatal error with the lowest dependencies

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#50]
https://github.com/TYPO3-Documentation/tea/runs/696878993?check_suite_focus=true

```
 Writing lock file
Generating autoload files
PHP Fatal error:  Uncaught Error: Class 'TYPO3\ClassAliasLoader\IncludeFile' not found in /home/runner/work/tea/tea/.Build/vendor/typo3/class-alias-loader/src/ClassAliasMapGenerator.php:135
```

**Comment by lukaszuznanski** [comment]
I think it can be close right now.

**Comment by oliverklee** [comment]
> I think it can be closed right now.

Why?

We're currently not running the CI with the lowest Composer dependencies, only with the highest dependency (i.e., the default). Or am I missing something here?
