### ISSUE TITLE
The changelog references PR but no links are created for that

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/tea#502]
e.g.

`Add the PHPStan strict rules (#471)`

That will not be rendered as a link if the changelog is viewed online: https://github.com/TYPO3-Documentation/tea/blob/main/CHANGELOG.md

Having a link to the issue or PR in the changelog might be convenient.

I believe, if that is changed like to square brackets` [#471]`, it should work:

`Add the PHPStan strict rules [#471]`

If agreed, I could create a PR for that.

(GitHub will automatically create links for issues / PR numbers with hash prefix (e.g. `#123` in commit messages, issues etc) but not if this format is used in .md files.)

See also https://github.com/olivierlacan/keep-a-changelog/issues/43 (which rather argues Changelogs should be self-contained and not provide link to issues at all, but here in tea we already reference the PR number, I think we might as well let it be a link)

**Comment by oliverklee** [comment]
@sypets Thanks for bringing this up. Yes, a PR for this would be awesome. Thanks a lot!

**Comment by oliverklee** [comment]
Closing as per the discussion in #503: We'd manually have to set the links, which is tedious and very error-prone. At least in the release notes, the issue/PR links already work fine.
