### ISSUE TITLE
Decide on how to handle bugfix version requirements

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/tea#529]
Right now we handle the bugfix version requirements differently for TYPO3 v10 and v11:

```
	"require": {
		"php": "~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0",
		"typo3/cms-core": "^10.4.11 || ^11.5.2",
		"typo3/cms-extbase": "^10.4.6 || ^11.5.2",
		"typo3/cms-fluid": "^10.4 || ^11.5.2",
		"typo3/cms-frontend": "^10.4 || ^11.5.2"
	},
```

Should we use minimal bugfix versions for extensions dependant on `typo3/cms-core` as is done here for v11 or not as done here for v10?

**Comment by oliverklee** [comment]
Fixed by #558.
