### ISSUE TITLE
Discussion: PHP version constraints

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/tea#530]
I am not satisfied with the current PHP version constraints in this extension, as it should serve as best practise.

Currently, it is:

```json
"require": {
    "php": "~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0",
}
```

I am convinced, that the following is better:

```json
"require": {
    "php": "^7.2 || ^8.0",
}
```

Main reasons:
- The current constraints blocks early adopters using the newest PHP version early in a project. Of course, one can fix the php platform configuration to, for example, `8.1` when using `8.2`. But that can have other drawbacks. When you follow the current `phpspec/prophecy` discussion you know what I mean. Or create a fork. Or copy the extension locally.
- Some extension developers (and agencies) are very slow adopting new PHP versions. This way, they receive bug reports and PRs early (hopefully).
- TYPO3 uses the `^8.1` PHP version constraint also (in main) and does not block new minor versions.

As by convention, a minor update should not break existing code, we should recommend the constraint above. If a new minor PHP version breaks an extension, this is considered as a bug, and should therefore be fixed.

Symfony goes one step further and declares (in current version 6):

```json
"require": {
    "php": ">=8.1",
}
```

This is debatable. Personally, I use the constraint in the Symfony way in my public extensions. And mostly, TYPO3 sets the main PHP constraint (actually `^8.1` for main).

**So, my recommendation is to use the `^7.2 || ^8.0` constraint as best practise.** What do you think?

**Comment by oliverklee** [comment]
Let's talk about this at our next call.

**Comment by linawolf** [comment]
Even if we reduce the version constraints for PHP we still have to decide which ones we run tests on.

**Comment by sbuerk** [comment]
Personally I would suggest use following constraint:

```json
"require": {
    "php": "^7.2 || ^7.3 || ^7.4 || ^8.0 || ^8.1",
}
```

Granted, there are superflous but it may be read as stated versions (X.Y.n) are "officially" supported, but still leave it open for early adoption of newer PHP versions. As soon as it is decieded that for e.g. PHP8.2 it gets expressivly added.

But that's more a personal expressive state.
