### ISSUE TITLE
Github workflows should not be restricted to branch main on push

### ISSUE THREAD

**Issue by sbuerk** [TYPO3-Documentation/tea#538]
At least the cross matrix ci runs should not be limited to "main" branch on push event. For example, if someone forks the repository, creates a branch and work on it (push) into his fork, github action will not be run (given that workflow are enabled in the fork).

This means, that people working in forks to contribute has to push removal of the main branch restriction and hopefully not forge it.

Should be thought about for codecoverage also.

On a pull-request all is executed.

**Comment by oliverklee** [comment]
Currently, the complete CI build should run when a PR is created or updated, and when a commit is pushed to the `main` branch (e.g., after a merge).

Having the CI build run for all branches by default would create duplicate CI runs for PRs, which seems like a waste of CI time to me.

So for running a build, you'll need to create a PR (which also can be a draft PR, just like the WIP changes on Gerrit).

Does this help?

Or am I missing something here?

**Comment by oliverklee** [comment]
Superseded by #545.
