### ISSUE TITLE
Create a 2.x branch

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#544]
As a best practice example for supporting older TYPO3 versions so that people can create PRs against that branch.

**Comment by linawolf** [comment]
I like that. In the Core main is also the newest development branch while 11.5 is the latest stable. 

Also it is quite chaotic to have all my changes for v12 compatibility in this one big PR. Could we move forward with this?

I would consider having one branch for each feature version (so 2.0, 2.1, ..) best practice event if we archive 2.0 after 2.1 has been publidhed... But I don't mind a 2.x branch either.

**Comment by oliverklee** [comment]
The intention of the 2.x branch is to easily allow contributors to backport fixes to the 2.x version after 3.0 development has started, allowing for new 2.x releases. As we follow semantic versioning, there is no need to have both e.g., a 2.0.7 and 2.1.5 release for the same fix, but only 2.1.5. So we don't need 2.0.x, 2.1.x etc. branches.

**Comment by linawolf** [comment]
So any plan on when we can start 3.0 Development? Now I still have it all fresh and would have a much easier time breaking up my epic PR https://github.com/TYPO3-Documentation/tea/pull/528 into smaller ones. On the same time as we are working on the documentation for v12 and v13 right now we do need a working branch that we can use as base for the automatically created code snippets...

Another possibility would be to work against a development branch while we still also develop features for the 2.x branch.

However, I really prefere to work on main and backport features whenever needed just like with the Core.

**Comment by oliverklee** [comment]
For this extension, we decided to have only one branch that actually is maintained (with the 2.x branch being there only as an example, but not a branch we actually expect to merge to). So we will probably start with 3.0 development once we’ve released 2.1 (which will come after 2.0.1 if there are no important fixes after 2.0.1 that would warrant a 2.0.2 release).

(We might also decide to skip 2.1 and move all those tasks to 3.1. We’ll discuss this at the call.)

Are you really already working on the V13 documentation?

**Comment by linawolf** [comment]
V13 Documentation? I think you mean version 12 and yes, I am working on it every day. My tea tutorial is written for version 12 and then back ported for version 11.

**Comment by oliverklee** [comment]
Now I'm confused. @linawolf You mentioned V13 here in your comment: https://github.com/TYPO3-Documentation/tea/issues/544#issuecomment-1236682959

**Comment by oliverklee** [comment]
Done.
