### ISSUE TITLE
Best practices for TCA 

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/tea#549]
We do have some best practices for TCA in listed in the TCA reference: 

https://docs.typo3.org/m/typo3/reference-tca/main/en-us/BestPractises/CommonFields.html

In my eyes it should be best practice to always offer support for enabling (fe_user, startdate, enddate, hidden) and when it makes sense for localization and workspaces.

There is broad support for these fields in Extbase as well.

https://docs.typo3.org/m/typo3/reference-tca/main/en-us/BestPractises/CommonFields.html

**Comment by oliverklee** [comment]
@linawolf Which fields specifically do you have in mind to add?

**Comment by linawolf** [comment]
Those fields and maybe additionally `t3_origuid` and the fields needed for localization: `sys_language_uid, l10n_parent, l10n_source, l10n_diffsource.`

**Comment by oliverklee** [comment]
Thanks. I've just split this ticket up into specific tasks: #551 #552 #553
