### ISSUE TITLE
Use typed properties instead of @var annotations

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/tea#550]
Tea v3 drops support for  PHP below 7.4 therefore typed properties are available now.

Let us replace the usage of `@var` annotations for properties and change them into typed properties according to https://review.typo3.org/c/Packages/TYPO3.CMS/+/74785

See also https://github.com/TYPO3-Documentation/tea/issues/454

**Comment by linawolf** [comment]
Union types for properties are allowed starting with PHP 8.0 we can therefore not remove the `@var` annotation from https://github.com/TYPO3-Documentation/tea/blob/lwolf-v12-compability/Classes/Domain/Model/Product/Tea.php#L29 while using phpstan yet. For Extbase it would be possible to use the optional type 
```
    protected ?\TYPO3\CMS\Extbase\Domain\Model\FileReference $image;
```

**Comment by oliverklee** [comment]
Using only the nullable type for `Tea::image` wont't work as this will crash when the image is lazy-loaded as first it's a `LazyLoadingProxy`). So we'll need to keep using `@var` annotations for this property.

**Comment by linawolf** [comment]
Ok so let's leave it like that then. I attached a commit to the epic Version 12 PR
