### ISSUE TITLE
Replace switchable controller actions

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/tea#569]
Switchable controller actions have been deprecated with v10.3 (See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Deprecation-89463-SwitchableControllerActions.html) and stopped working with v12. I would suggest we already replace them for 2.1.0 as they have been deprecated for all supported versions

**Comment by oliverklee** [comment]
Moving to 3.0 as this is a breaking change.
