### ISSUE TITLE
Error if I try to execute scripts with ddev composer ...

### ISSUE THREAD

**Issue by kanow** [TYPO3-Documentation/tea#571]
I cloned the master branch from github and trying to execute the tests as described in documentation with the following command.

`ddev composer ci`

There are some confirmations needed

`Do you trust "phpstan/extension-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]`

I confirmed that all with "y". I also tried to confirm that with "d". But the same result.

But the script ends with an error

`Script @composer normalize --dry-run handling the ci:composer:normalize event returned with error code 1
Script @ci:composer:normalize was called via ci:static
Script @ci:static was called via ci
composer [ci] failed, composer command failed: exit status 1. stderr= 
`
Whats's going wrong?

I'm working on Ubuntu 20.04 with Ddev 1.21.1

**Comment by oliverklee** [comment]
I've just tested `ddev composer ci`, `ddev composer ci:static` and `ddev composer dynamic`: All three work without problems on my system (Ubuntu 22.04, DDEV 1.21.1).

@kanow Could you please check that you have the latest version of the `main` branch (not `master`) with the latest commit from September 19th (or later), and that you have run `ddev composer update --with-dependencies`?

**Comment by kanow** [comment]
Mahlzeit!

Yes, thx. That helps. I'm on an very old commit in main branch. Last commit 12 month old. I don't know why but now everything is working fine.

**Comment by oliverklee** [comment]
Thanks for the update. That's good to hear!
