### ISSUE TITLE
Functional with composer min and  PHP8.1 failing

### ISSUE THREAD

**Issue by sbuerk** [TYPO3-Documentation/tea#635]
Functional tests executed with PHP8.1 and composer minimum installs
failing with corresponding interface change isses with symfony/routing
package.

To mitigate this the minimum required core version should be at least
slightly increased from 11.5.2 to 11.5.3 to have the needed minimum
3rd party package constraints to avoid this issue (having corresponding
fixes available).

```
Fatal error: During inheritance of IteratorAggregate: Uncaught Return type of Symfony\Component\Routing\RouteCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Return type of Symfony\Component\Routing\RouteCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

**Comment by oliverklee** [comment]
I wonder why this problem does not occur on the CI with PHP 8.1, TYPO3 11LTS, lowest dependencies: https://github.com/TYPO3-Documentation/tea/actions/runs/3256317516/jobs/5346620160
