### ISSUE TITLE
Replace usages of the `@internal` `\TYPO3\CMS\Extbase\Domain\Model\FileReference`

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/tea#658]
`FileReference` is internal in TYPO3 11.5. So it is not best practice to use it anymore.

**Comment by linawolf** [comment]
So shall we implement FileReference ourselves then?

**Comment by brotkrueml** [comment]
Can you add the FQCN?

**Comment by oliverklee** [comment]
`\TYPO3\CMS\Extbase\Domain\Model\FileReference` seems was marked as internal ages ago:
https://github.com/TYPO3/typo3/commit/65a5511149dbabeb58fc86d9c4f66188ea040d90#diff-3888dae8f3f71c3f5e1db1c00bcbfe7d0d8fed2e5966e6533c9353b6d7485f32

There does not seem to be a suggested replacement, though. So I propose we keep using it until Extbase provides a replacement.

**Comment by oliverklee** [comment]
I think it was marked as experimental in the beginning, then changed from experimental to internal in the cleanup, and never de-internal-ized. Maybe we should change that.

**Comment by oliverklee** [comment]
> Other models for system tables have also been removed.

Those (FE user etc.) were explicitly deprecated because those models are expected to have extension-specific versions with more/less fields. My guess for `FileReference` is that this is different (because we'd be copying the code from Core without any changes) and that having them internal was not a dedicated decision.

**Comment by linawolf** [comment]
Unfortunary no

**Comment by oliverklee** [comment]
I've now  created a change to not mark those classes as `@internal` anymore in the Core: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76670
