### ISSUE TITLE
Rethink the name "tea"?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/tea#683]
reasons: 

* there is a package manager named "tea", see https://tea.xyz/
* a name usually reflects what the extension does and what it is for. 
* a unique speaking name also makes it easier to search for it.

I think something which has the name "example" or "best practice" in it might be useful. Renaming an extension can a hassle (because some derived names change too), but doable.

I am also not sure what `ttn` is, this extension is in the TYPO3-Documentation workspace which usually uses t3docs, see

* https://github.com/TYPO3-Documentation/t3docs-examples/blob/main/composer.json
* https://github.com/TYPO3-Documentation/blog_example/blob/main/composer.json

**Comment by oliverklee** [comment]
Thanks for bringing this up.

We've discussed this in our call and decided to keep the extension name. We still think that we should document why we've chosen the name, and why it serves as a good example. I've created [an issue](#692) for that.

**Comment by DanielSiepmann** [comment]
We decided to keep the name as we don't think changing is worth the effort. We also think it makes sense to clearly state that this is an example best practice extension. But one part of that is to provide a proper name within the context. This extension is about tea, so this makes sense.
We also checked that we clearly state that this is an best practice example:

- https://extensions.typo3.org/extension/tea
- https://packagist.org/packages/ttn/tea
- https://github.com/TYPO3-Documentation/tea
- https://docs.typo3.org/p/ttn/tea/main/en-us/

Please comment if there are further places I've missed.
