### ISSUE TITLE
Tea Single View does not work

### ISSUE THREAD

**Issue by averlon** [TYPO3-Documentation/tea#769]
Hi,
I am currently trying to get familiar with extension development and scroll a lot of documentation. Also about Tea.

1) The documentation on
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/Tutorials/Tea/Controller.html

does not seem to correspond with the current release of tea.

2) the plugin of tea for Single View throws an exception.
[TYPO3 Exception.txt](https://github.com/TYPO3-Documentation/tea/files/10931960/TYPO3.Exception.txt)
I guess, since there is no option in the BE-View for Single View Plugin to select a Tea content element, this might be the root cause for this.

**Comment by averlon** [comment]
wrong configuration of composer.json with wrong php-version. Therefore only 2.0.0 was installed.
After change of config and correct settings of constants editor for tea also single view works.

**Comment by averlon** [comment]
sorry, I have to reopen.
Single view still does not work.
Installed: 3.0.0
[TYPO3 Exception.txt](https://github.com/TYPO3-Documentation/tea/files/10932765/TYPO3.Exception.txt)

**Comment by oliverklee** [comment]
@averlon Which versions of TYPO3 and PHP are you using?

And you're using a Composer-based installation, I gather, right?

And which version of tea are you Composer-requiring?

**Comment by averlon** [comment]
Hallo Oliver,
war ein Fehler in meiner Testumgebung, weil ich dort gerade den Versuch unternehme eine eigene Extension zu entwickeln.
Tea 3.0.0 funktioniert jetzt.
