### ISSUE TITLE
PHP 8.1 tests on GitLab CI are missing the ext-intl PHP extension

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#789]
https://git.typo3.org/qa/example-extension/-/jobs/2117134

**Comment by lukaszuznanski** [comment]
Looks like ext-intl is not enough to solve this issue.

**Comment by oliverklee** [comment]
@lukaszuznanski Does adding ext-intl at least help (so we can see the next error to work on)?
