### ISSUE TITLE
Reduce the GitHub actions builds

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#83]
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration

Maybe we can reduce executing the same action twice.

**Comment by lukaszuznanski** [comment]
Right now we are running on every single action, so when I push some code and create PR, then we have build, after merge to master there is another build. You are saying that we should disable for example merge to master build?
