### ISSUE TITLE
Fix the find command for the yaml lint composer script

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#91]
The path exclusion needs to come before the file name matcher (otherwise it won't work).

Broken:
```bash
find . -name '*.yml' -not -path '*.Build/*'
```

Fixed:
```bash
find . -not -path '*.Build/*' -name '*.yml'
```

Even short (using `!` instead of `-not`):
```bash
find . ! -path '*.Build/*' -name '*.yml'
```

**Comment by lukaszuznanski** [comment]
Are you sure that this is broken? It's working fine for me on local os, and I can see that it's checking files excluding Build directory in github actions, also json lint is using the same order of parameters. Anyway I like your version more than current state so I will provide PR.

**Comment by oliverklee** [comment]
I was wrong about the correct command. This should work instead.
```bash
find . ! -path './var/*' ! -path './vendor/*' \(  -name '*.yml' -o -name '*.yaml' \)
```
