### ISSUE TITLE
Add a GitLab CI status badge or link to the README.md

### ISSUE THREAD

**Issue by oliverklee** [TYPO3-Documentation/tea#96]
The button markup should be available in GitLab.
This (hopefully) is the link to the pipelines: https://gitlab.typo3.org/qa/example-extension/-/pipelines/

**Comment by lukaszuznanski** [comment]
Right now we can't add gitlab CI status badge, because URL to svg file is not publicly accessible
https://gitlab.typo3.org/qa/example-extension/badges/master/pipeline.svg
